image: ruby:2.6

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - bundler
        script:
          - bundle install --path=./vendor
          - bundle exec rake build
          - bundle exec rake spec
    - step:
        name: Verification
        caches:
          - bundler
        script:
          - bundle install --path=./vendor
          - bundle exec rake yard
          - bundle exec rake rubocop

definitions:
  caches:
    bundler: ./vendor
