image: ruby:2.6

pipelines:
  branches:
    master:
      - step:
          name: Test stable
          deployment: production
          caches:
            - bundler
          script:
            - bundle install --path=./vendor
            - bundle exec rake build
            - bundle exec rake spec
            - bundle exec rake yard
            - bundle exec rake rubocop
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"pkg/*.gem"
    develop:
      - step:
          name: Development test
          deployment: test-dev
          caches:
            - bundler
          script:
            - bundle install --path=./vendor
            - bundle exec rake build
            - bundle exec rake spec
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"pkg/*.gem"
    feature/*:
      - step:
          name: Feature test
          deployment: test-feature
          caches:
            - bundler
          script:
            - bundle install --path=./vendor
            - bundle exec rake build
            - bundle exec rake spec
    release/*:
      - step:
          name: Test upcoming release
          deployment: staging
          caches:
            - bundler
          script:
            - bundle install --path=./vendor
            - bundle exec rake build
            - bundle exec rake spec
            - bundle exec rake yard
            - bundle exec rake rubocop
  default:
    - step:
        name: Build and test
        caches:
          - bundler
        script:
          - bundle install --path=./vendor
          - bundle exec rake build
          - bundle exec rake spec
          - bundle exec rake yard
          - bundle exec rake rubocop

definitions:
  caches:
    bundler: ./vendor
