version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install bundler -v 2.0.1
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rake build
      - bundle exec rake spec
      - bundle exec rake yard
      - bundle exec rake rubocop

artifacts:
  files:
    - pkg/*.gem
  discard-paths: yes
  #base-directory: location
